
//package
export const GET_ALL_PACKAGES = "GET_ALL_PACKAGES";
export const GET_PACKAGE_BYID="GET_PACKAGE_BYID";
export const POST_PACKAGE="POST_PACKAGE";
export const PUT_PACKAGE="PUT_PACKAGE";

//accessory
export const GET_ALL_ACCESSORIES= 'GET_ALL_ACCESSORIES';
export const PUT_ACCESSORIES='PUT_ACCESSORIES';
export const POST_ACCESSORIES='POST_ACCESSORIES';
export const GET_ACCESSORIES_BYID='GET_ACCESSORIES_BYID';

export const GET_CALENDAR="GET_CALENDAR";

export const GET_TRIP_BYPACKAGEID="GET_TRIP_BYPACKAGEID";
//trip

export const GET_TRIP_BYID="GET_TRIP_BYID";
export const GET_TRIP="GET_TRIP";
export const POST_TRIP="POST_TRIP";
export const PUT_TRIP="PUT_TRIP";

//itenary
export const GET_ITENARY_BYPACKAGEID="GET_ITENARY_BYPACKAGEID";
export const GET_ITENARY="GET_ITENARY";
export const GET_ITENARY_BYID="GET_ITENARY_BYID";
export const POST_ITENARY="POST_ITENARY";
export const PUT_ITENARY="PUT_ITENARY";


//activity
export const GET_AVCTIVITIES="GET_AVCTIVITIES";
export const GET_ACTIVITY_BYID="GET_ACTIVITY_BYID";
export const POST_ACTIVITY="POST_ACTIVITY";
export const PUT_ACTIVITY="PUT_ACTIVITY";

//costcentre
export const GET_COSTCENTRE="GET_COSTCENTRE";
export const POST_COSTCENTRE="POST_COSTCENTRE";
export const PUT_COSTCENTRE="PUT_COSTCENTRE";
export const GET_COSTCENTRE_BYID="GET_COSTCENTRE_BYID";

//country
export const GET_COUNTRIES="GET_COUNTRIES";
export const GET_COUNTRY_BYID="GET_COUNTRY_BYID";
export const POST_COUNTRY="POST_COUNTRY";
export const PUT_COUNTRY="PUT_COUNTRY";

//city
export const GET_CITIES="GET_CITIES";
export const GET_CITY_BYID="GET_CITY_BYID";
export const GET_CITY_STATEID="GET_CITY_STATEID";
export const POST_CITY="POST_CITY";
export const PUT_CITY="PUT_CITY";
export const RESET_CITY="RESET_CITY";

//coupon
export const GET_ALL_COUPON="GET_ALL_COUPON";
export const GET_COUPON_BYID="GET_COUPON_BYID";
export const POST_COUPON="POST_COUPON";
export const PUT_COUPON="PUT_COUPON";

//eventlevel
export const GET_EVENTLEVEL="ET_EVENTLEVEL";
export const GET_EVENTLEVEL_BYID="GET_EVENTLEVEL_BYID";
export const POST_EVENTLEVEL="POST_EVENTLEVEL";
export const PUT_EVENTLEVEL="PUT_EVENTLEVEL";

//status
export const GET_STATUS="GET_STATUS";

//eventtype
export const GET_EVENTTYPE="GET_EVENTTYPE";
export const POST_EVENTTYPE="POST_EVENTTYPE";
export const PUT_EVENTTYPE="PUT_EVENTTYPE";
export const GET_EVENTTYPE_BYID="GET_EVENTTYPE_BYID";

//placetovisit
export const GET_PLACETOVISIT="GET_PLACETOVISIT";
export const POST_PLACETOVISIT="POST_PLACETOVISIT";
export const PUT_PLACETOVISIT="PUT_PLACETOVISIT";
export const GET_PLACETOVISIT_BYID="GET_PLACETOVISIT_BYID";

//placetype
export const GET_PLACETYPE="GET_PLACETYPE";
export const POST_PLACETYPE="POST_PLACETYPE";
export const PUT_PLACETYPE="PUT_PLACETYPE";
export const GET_PLACETYPE_BYID="GET_PLACETYPE_BYID";

//state
export const GET_STATES="GET_STATES";
export const GET_STATE_BYID="GET_STATE_BYID";
export const GET_STATE_BYCOUNTRYID="GET_STATE_BYCOUNTRYID";
export const POST_STATE="POST_STATE";
export const PUT_STATE="PUT_STATE";

//stay
export const GET_STAY="GET_STAY";
export const POST_STAY="POST_STAY";
export const GET_STAY_BYID="GET_STAY_BYID";
export const PUT_STAY="PUT_STAY";

//staytype
export const GET_STAYTYPE="GET_STAYTYPE";
export const GET_STAYTYPE_BYID="GET_STAYTYPE_BYID";
export const POST_STAYTYPE="POST_STAYTYPE";
export const PUT_STAYTYPE="PUT_STAYTYPE";

//travelinfo
export const GET_TRAVELINFO="GET_TRAVELINFO";
export const GET_TRAVELINFO_BYID="GET_TRAVELINFO_BYID";
export const POST_TRAVELINFO="POST_TRAVELINFO";
export const PUT_TRAVELINFO="PUT_TRAVELINFO";

//traveltype
export const GET_TRAVELTYPE="GET_TRAVELTYPE";
export const GET_TRAVELTYPE_BYID="GET_TRAVELTYPE_BYID";
export const POST_TRAVELTYPE="POST_TRAVELTYPE";
export const PUT_TRAVELTYPE="PUT_TRAVELTYPE"

//destination
export const GET_DESTINATION="GET_DESTINATION";
export const GET_DESTINATION_BYID="GET_DESTINATION_BYID";
export const POST_DESTINATION="POST_DESTINATION";
export const PUT_DESTINATION="PUT_DESTINATION";




export const GET_ALL_DESTINATION="GET_ALL_DESTINATION";

export const UPDATE_PROP="UPDATE_PROP";
export const UPDATE_PROP_ACC="UPDATE_PROP_ACC";

export const RESET_DATA="RESET_DATA";


//post




//put
