export const GET_ALL_PACKAGES = 'GET_ALL_PACKAGES';
export const GET_ALL_ACCESSORIES= 'GET_ALL_ACCESSORIES';
export const GET_CALENDAR="GET_CALENDAR";
export const GET_ITENARY_BYPACKAGEID="GET_ITENARY_BYPACKAGEID";
export const GET_PACKAGE_BYID="GET_PACKAGE_BYID";
export const GET_TRIP_BYPACKAGEID="GET_TRIP_BYPACKAGEID";
export const GET_TRIP_BYID="GET_TRIP_BYID";
export const GET_AVCTIVITIES="GET_AVCTIVITIES";
export const GET_CITIES="GET_CITIES";
export const GET_CITY_BYID="GET_CITY_BYID";
export const GET_CITY_STATEID="GET_CITY_STATEID";
export const GET_COUNTRIES="GET_COUNTRIES";
export const GET_STATES="GET_STATES";
export const GET_COUNTRY_BYID="GET_COUNTRY_BYID";
export const GET_ALL_COUPON="GET_ALL_COUPON";
export const GET_COUPON_BYID="GET_COUPON_BYID";
export const GET_ALL_DESTINATION="GET_ALL_DESTINATION";


